/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikacja;

import adm.Baks.BaksSessionBean;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author jmaj
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelMain = new javax.swing.JPanel();
        menuBarMain = new javax.swing.JMenuBar();
        naprawaMenu = new javax.swing.JMenu();
        zapiszMenuItem = new javax.swing.JMenuItem();
        przegladajMenuItem = new javax.swing.JMenuItem();
        historiaMenu = new javax.swing.JMenu();
        przegladajHistItem = new javax.swing.JMenuItem();
        pracaMenu = new javax.swing.JMenu();
        pracaItem = new javax.swing.JMenuItem();
        mojeDaneMenu = new javax.swing.JMenu();
        edytujDaneItem = new javax.swing.JMenuItem();
        zmianaHaslaItem = new javax.swing.JMenuItem();
        uzytkownicyAdm = new javax.swing.JMenu();
        klienciPrzegladajItem = new javax.swing.JMenuItem();
        dodajUzytkownikaItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        fakturaItem = new javax.swing.JMenuItem();
        wylogujMenu = new javax.swing.JMenu();
        wylogujItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baks - warsztat motocyklowy");
        setMinimumSize(new java.awt.Dimension(1024, 700));
        setPreferredSize(new java.awt.Dimension(1024, 700));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panelMain.setBackground(BaksSessionBean
            .MAIN_BACKGROUND_PANEL_COLOR);
        panelMain.setMinimumSize(new java.awt.Dimension(1024, 700));
        panelMain.setPreferredSize(new java.awt.Dimension(1024, 700));
        panelMain.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panelMain, gridBagConstraints);

        naprawaMenu.setText("Naprawa");

        zapiszMenuItem.setText("Zapisz");
        naprawaMenu.add(zapiszMenuItem);

        przegladajMenuItem.setText("Przeglądaj");
        naprawaMenu.add(przegladajMenuItem);

        menuBarMain.add(naprawaMenu);

        historiaMenu.setText("Historia");

        przegladajHistItem.setText("Przeglądaj");
        historiaMenu.add(przegladajHistItem);

        menuBarMain.add(historiaMenu);

        pracaMenu.setText("Praca");

        pracaItem.setText("Praca");
        pracaMenu.add(pracaItem);

        menuBarMain.add(pracaMenu);

        mojeDaneMenu.setText("Moje dane");

        edytujDaneItem.setText("Edytuj");
        mojeDaneMenu.add(edytujDaneItem);

        zmianaHaslaItem.setText("Zmiana hasła");
        mojeDaneMenu.add(zmianaHaslaItem);

        menuBarMain.add(mojeDaneMenu);

        uzytkownicyAdm.setText("Użytkownicy");

        klienciPrzegladajItem.setText("Dane użytkowników");
        uzytkownicyAdm.add(klienciPrzegladajItem);

        dodajUzytkownikaItem.setText("Dodaj użytkownika");
        uzytkownicyAdm.add(dodajUzytkownikaItem);

        menuBarMain.add(uzytkownicyAdm);

        jMenu1.setText("Płatności");

        fakturaItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        fakturaItem.setText("Faktury");
        jMenu1.add(fakturaItem);

        menuBarMain.add(jMenu1);

        wylogujMenu.setText("Wyloguj");
        wylogujMenu.setToolTipText("Wyloguj z aplikacji");
        wylogujMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        wylogujItem.setText("Wyloguj");
        wylogujMenu.add(wylogujItem);

        menuBarMain.add(wylogujMenu);

        setJMenuBar(menuBarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JMenuItem getEdytujDaneItem() {
        return edytujDaneItem;
    }

    public JMenuItem getZmianaHaslaItem() {
        return zmianaHaslaItem;
    }

    public JMenuItem getWylogujItem() {
        return wylogujItem;
    }

    public void setWylogujItem(JMenuItem wylogujItem) {
        this.wylogujItem = wylogujItem;
    }

    public void setZmianaHaslaItem(JMenuItem zmianaHaslaItem) {
        this.zmianaHaslaItem = zmianaHaslaItem;
    }

    public void setEdytujDaneItem(JMenuItem edytujDaneItem) {
        this.edytujDaneItem = edytujDaneItem;
    }

    public JMenu getHistoriaMenu() {
        return historiaMenu;
    }

    public void setHistoriaMenu(JMenu historiaMenu) {
        this.historiaMenu = historiaMenu;
    }

    public JMenuItem getPracaItem() {
        return pracaItem;
    }

    public void setPracaItem(JMenuItem pracaItem) {
        this.pracaItem = pracaItem;
    }

    public JMenu getPracaMenu() {
        return pracaMenu;
    }

    public void setPracaMenu(JMenu pracaMenu) {
        this.pracaMenu = pracaMenu;
    }

    public JMenu getjMenu1() {
        return uzytkownicyAdm;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.uzytkownicyAdm = jMenu1;
    }

    public JPanel getjPanelMain() {
        return panelMain;
    }

    public void setjPanelMain(JPanel jPanel1) {
        this.panelMain = jPanel1;
    }

    public JMenuItem getDaneUzytkownikowAdmItem() {
        return klienciPrzegladajItem;
    }

    public JMenuItem getFakturaItem() {
        return fakturaItem;
    }

    public JMenuItem getKlienciPrzegladajItem() {
        return klienciPrzegladajItem;
    }

    public void setKlienciPrzegladajItem(JMenuItem klienciPrzegladajItem) {
        this.klienciPrzegladajItem = klienciPrzegladajItem;
    }

    public JMenuBar getMenuBarMain() {
        return menuBarMain;
    }

    public void setMenuBarMain(JMenuBar menuBarMain) {
        this.menuBarMain = menuBarMain;
    }

    public JMenu getMojeDaneMenu() {
        return mojeDaneMenu;
    }

    public void setMojeDaneMenu(JMenu mojeDaneMenu) {
        this.mojeDaneMenu = mojeDaneMenu;
    }

    public JMenu getNaprawaMenu() {
        return naprawaMenu;
    }

    public void setNaprawaMenu(JMenu naprawaMenu) {
        this.naprawaMenu = naprawaMenu;
    }

    public JMenuItem getPrzegladajHistItem() {
        return przegladajHistItem;
    }

    public JMenu getUzytkownicyAdm() {
        return uzytkownicyAdm;
    }

    public void setUzytkownicyAdm(JMenu uzytkownicyAdm) {
        this.uzytkownicyAdm = uzytkownicyAdm;
    }

    public void setPrzegladajHistItem(JMenuItem przegladajHistItem) {
        this.przegladajHistItem = przegladajHistItem;
    }

    public JMenuItem getPrzegladajMenuItem() {
        return przegladajMenuItem;
    }

    public void setPrzegladajMenuItem(JMenuItem przegladajMenuItem) {
        this.przegladajMenuItem = przegladajMenuItem;
    }

    public JMenu getWylogujMenu() {
        return wylogujMenu;
    }

    public void setWylogujMenu(JMenu wylogujMenu) {
        this.wylogujMenu = wylogujMenu;
    }

    public JMenuItem getZapiszMenuItem() {
        return zapiszMenuItem;
    }

    public void setZapiszMenuItem(JMenuItem zapiszMenuItem) {
        this.zapiszMenuItem = zapiszMenuItem;
    }

    public JMenuItem getDodajUzytkownikaItem() {
        return dodajUzytkownikaItem;
    }

    public void setDodajUzytkownikaItem(JMenuItem dodajUzytkownikaItem) {
        this.dodajUzytkownikaItem = dodajUzytkownikaItem;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dodajUzytkownikaItem;
    private javax.swing.JMenuItem edytujDaneItem;
    private javax.swing.JMenuItem fakturaItem;
    private javax.swing.JMenu historiaMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem klienciPrzegladajItem;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu mojeDaneMenu;
    private javax.swing.JMenu naprawaMenu;
    private javax.swing.JPanel panelMain;
    private javax.swing.JMenuItem pracaItem;
    private javax.swing.JMenu pracaMenu;
    private javax.swing.JMenuItem przegladajHistItem;
    private javax.swing.JMenuItem przegladajMenuItem;
    private javax.swing.JMenu uzytkownicyAdm;
    private javax.swing.JMenuItem wylogujItem;
    private javax.swing.JMenu wylogujMenu;
    private javax.swing.JMenuItem zapiszMenuItem;
    private javax.swing.JMenuItem zmianaHaslaItem;
    // End of variables declaration//GEN-END:variables
}
