/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platnosci.zarzadzanie;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Robert M
 */
public class ZarzadzaniePlatnosciaPanel extends javax.swing.JPanel {

    /**
     * Creates new form NaprawaZapisPanel
     */
    public ZarzadzaniePlatnosciaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnRezygnuj = new javax.swing.JButton();
        btnZapisz = new javax.swing.JButton();
        btnEdytuj = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radioZaplacone = new javax.swing.JRadioButton();
        radioNieZaplacone = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        radioAnulowane = new javax.swing.JRadioButton();
        firmaComboBox = new javax.swing.JComboBox();
        btnDodajFirme = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kwotaText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        terminPlatnosciDate = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        nrFakturyText = new javax.swing.JTextField();
        dataZaplatyLabel = new javax.swing.JLabel();
        dataZaplatyChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Płatności"));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        panelBtn.setBackground(new java.awt.Color(102, 102, 102));

        btnRezygnuj.setText("Rezygnuj");

        btnZapisz.setText("Zapisz");

        btnEdytuj.setText("Edytuj");

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(btnEdytuj)
                .addGap(18, 18, 18)
                .addComponent(btnZapisz)
                .addGap(18, 18, 18)
                .addComponent(btnRezygnuj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRezygnuj)
                    .addComponent(btnZapisz)
                    .addComponent(btnEdytuj))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        buttonGroup1.add(radioZaplacone);
        radioZaplacone.setText("Zapłacone");

        buttonGroup1.add(radioNieZaplacone);
        radioNieZaplacone.setText("Nie zapłacone");

        jLabel3.setText("Status");

        buttonGroup1.add(radioAnulowane);
        radioAnulowane.setText("Anulowane");

        firmaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodajFirme.setText("Dodaj firmę");

        jLabel2.setText("Firma");

        jLabel5.setText("Kwota");

        jLabel6.setText("Termin płatności");

        jLabel4.setText("Nr faktury");

        dataZaplatyLabel.setText("Termin zapłaty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioZaplacone)
                        .addGap(18, 18, 18)
                        .addComponent(radioNieZaplacone)
                        .addGap(18, 18, 18)
                        .addComponent(radioAnulowane))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4)
                            .addComponent(dataZaplatyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kwotaText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(terminPlatnosciDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nrFakturyText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firmaComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 380, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajFirme))
                            .addComponent(dataZaplatyChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioZaplacone)
                    .addComponent(radioNieZaplacone)
                    .addComponent(jLabel3)
                    .addComponent(radioAnulowane))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firmaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajFirme)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nrFakturyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kwotaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(terminPlatnosciDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataZaplatyLabel)
                    .addComponent(dataZaplatyChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDodajFirme() {
        return btnDodajFirme;
    }

    public void setBtnDodajFirme(JButton btnDodajFirme) {
        this.btnDodajFirme = btnDodajFirme;
    }

    public JButton getBtnEdytuj() {
        return btnEdytuj;
    }

    public void setBtnEdytuj(JButton btnEdytuj) {
        this.btnEdytuj = btnEdytuj;
    }

    public JButton getBtnRezygnuj() {
        return btnRezygnuj;
    }

    public void setBtnRezygnuj(JButton btnRezygnuj) {
        this.btnRezygnuj = btnRezygnuj;
    }

    public JButton getBtnZapisz() {
        return btnZapisz;
    }

    public void setBtnZapisz(JButton btnZapisz) {
        this.btnZapisz = btnZapisz;
    }

    public JComboBox getFirmaComboBox() {
        return firmaComboBox;
    }

    public void setFirmaComboBox(JComboBox firmaComboBox) {
        this.firmaComboBox = firmaComboBox;
    }

    public JTextField getKwotaText() {
        return kwotaText;
    }

    public void setKwotaText(JTextField kwotaText) {
        this.kwotaText = kwotaText;
    }

    public JPanel getPanelBtn() {
        return panelBtn;
    }

    public void setPanelBtn(JPanel panelBtn) {
        this.panelBtn = panelBtn;
    }

    public JRadioButton getRadioAnulowane() {
        return radioAnulowane;
    }

    public void setRadioAnulowane(JRadioButton radioAnulowane) {
        this.radioAnulowane = radioAnulowane;
    }

    public JRadioButton getRadioNieZaplacone() {
        return radioNieZaplacone;
    }

    public void setRadioNieZaplacone(JRadioButton radioNieZaplacone) {
        this.radioNieZaplacone = radioNieZaplacone;
    }

    public JRadioButton getRadioZaplacone() {
        return radioZaplacone;
    }

    public void setRadioZaplacone(JRadioButton radioZaplacone) {
        this.radioZaplacone = radioZaplacone;
    }

    public JDateChooser getTerminPlatnosciDate() {
        return terminPlatnosciDate;
    }

    public void setTerminPlatnosciDate(JDateChooser terminPlatnosciDate) {
        this.terminPlatnosciDate = terminPlatnosciDate;
    }

    public JTextField getNrFakturyText() {
        return nrFakturyText;
    }

    public void setNrFakturyText(JTextField nrFakturyText) {
        this.nrFakturyText = nrFakturyText;
    }

    public JDateChooser getDataZaplatyChooser() {
        return dataZaplatyChooser;
    }

    public void setDataZaplatyChooser(JDateChooser dataZaplatyChooser) {
        this.dataZaplatyChooser = dataZaplatyChooser;
    }

    public JLabel getDataZaplatyLabel() {
        return dataZaplatyLabel;
    }

    public void setDataZaplatyLabel(JLabel dataZaplatyLabel) {
        this.dataZaplatyLabel = dataZaplatyLabel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajFirme;
    private javax.swing.JButton btnEdytuj;
    private javax.swing.JButton btnRezygnuj;
    private javax.swing.JButton btnZapisz;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dataZaplatyChooser;
    private javax.swing.JLabel dataZaplatyLabel;
    private javax.swing.JComboBox firmaComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kwotaText;
    private javax.swing.JTextField nrFakturyText;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JRadioButton radioAnulowane;
    private javax.swing.JRadioButton radioNieZaplacone;
    private javax.swing.JRadioButton radioZaplacone;
    private com.toedter.calendar.JDateChooser terminPlatnosciDate;
    // End of variables declaration//GEN-END:variables
}
