/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naprawa.praca;

import adm.Baks.BaksSessionBean;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author mzuralski
 */
public class PodsumowaniePanel extends javax.swing.JPanel {

    /**
     * Creates new form GeografiaStrukturaPanel
     */
    public PodsumowaniePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupCenaProcent = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCzesci = new javax.swing.JTable();
        panelNaprawa = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableNaprawa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMaterialy = new javax.swing.JTable();
        panelPodsumowanie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        podsumowanieKoszt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        naprawaKoszt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        materialyKoszt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        czesciKoszt = new javax.swing.JTextField();
        labelDoZaplaty = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        marzaCzesc = new javax.swing.JTextField();
        cenaCzesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rabat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnRabat = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        poRabacieRazem = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(98, 600));
        setPreferredSize(new java.awt.Dimension(240, 600));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(BaksSessionBean.GREEN_CIEM_COLOR);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Części", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 100));

        tableCzesci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(tableCzesci);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(jPanel4, gridBagConstraints);

        panelNaprawa.setBackground(BaksSessionBean.BROWN_CIEM_COLOR);
        panelNaprawa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Naprawa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        panelNaprawa.setLayout(new java.awt.GridBagLayout());

        jScrollPane5.setPreferredSize(new java.awt.Dimension(100, 100));

        tableNaprawa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tableNaprawa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelNaprawa.add(jScrollPane5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(panelNaprawa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(BaksSessionBean.BROWN_CIEM_COLOR);
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materiały", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(100, 100));

        tableMaterialy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(tableMaterialy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jScrollPane4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jPanel5, gridBagConstraints);

        panelPodsumowanie.setBackground(BaksSessionBean.GREEN_CIEM_COLOR);
        panelPodsumowanie.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Podsumowanie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        panelPodsumowanie.setMinimumSize(new java.awt.Dimension(23, 23));
        panelPodsumowanie.setPreferredSize(new java.awt.Dimension(200, 100));
        panelPodsumowanie.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Części");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel1, gridBagConstraints);

        podsumowanieKoszt.setEditable(false);
        podsumowanieKoszt.setBackground(new java.awt.Color(204, 255, 255));
        podsumowanieKoszt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        podsumowanieKoszt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        podsumowanieKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(podsumowanieKoszt, gridBagConstraints);

        jLabel2.setText("Materiały");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel2, gridBagConstraints);

        naprawaKoszt.setEditable(false);
        naprawaKoszt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        naprawaKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(naprawaKoszt, gridBagConstraints);

        jLabel3.setText("Naprawa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel3, gridBagConstraints);

        materialyKoszt.setEditable(false);
        materialyKoszt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        materialyKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(materialyKoszt, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PODSUMOWANIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel4, gridBagConstraints);

        czesciKoszt.setEditable(false);
        czesciKoszt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        czesciKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(czesciKoszt, gridBagConstraints);

        labelDoZaplaty.setBackground(new java.awt.Color(255, 204, 204));
        labelDoZaplaty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDoZaplaty.setText("Do zapłaty:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(34, 0, 9, 0);
        panelPodsumowanie.add(labelDoZaplaty, gridBagConstraints);

        jLabel6.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        panelPodsumowanie.add(jLabel6, gridBagConstraints);

        jLabel7.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        panelPodsumowanie.add(jLabel7, gridBagConstraints);

        jLabel8.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        panelPodsumowanie.add(jLabel8, gridBagConstraints);

        jLabel9.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        panelPodsumowanie.add(jLabel9, gridBagConstraints);

        marzaCzesc.setEditable(false);
        marzaCzesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        marzaCzesc.setMinimumSize(new java.awt.Dimension(120, 20));
        marzaCzesc.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(marzaCzesc, gridBagConstraints);

        cenaCzesc.setEditable(false);
        cenaCzesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cenaCzesc.setMinimumSize(new java.awt.Dimension(120, 20));
        cenaCzesc.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(cenaCzesc, gridBagConstraints);

        jLabel5.setText("Cena");
        jLabel5.setPreferredSize(new java.awt.Dimension(84, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel5, gridBagConstraints);

        jLabel10.setText("Marża");
        jLabel10.setPreferredSize(new java.awt.Dimension(84, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel10, gridBagConstraints);

        jLabel11.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        panelPodsumowanie.add(jLabel11, gridBagConstraints);

        jLabel12.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        panelPodsumowanie.add(jLabel12, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        panelPodsumowanie.add(jSeparator1, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Szczegóły ceny");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelPodsumowanie.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("PODSUMOWANIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        panelPodsumowanie.add(jLabel14, gridBagConstraints);

        rabat.setEditable(false);
        rabat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(rabat, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Rabat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel15, gridBagConstraints);

        jLabel16.setText("%");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        panelPodsumowanie.add(jLabel16, gridBagConstraints);

        btnRabat.setText("Dodaj rabat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(3, 28, 3, 5);
        panelPodsumowanie.add(btnRabat, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("RAZEM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel17, gridBagConstraints);

        poRabacieRazem.setEditable(false);
        poRabacieRazem.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(poRabacieRazem, gridBagConstraints);

        jLabel18.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        panelPodsumowanie.add(jLabel18, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.53;
        jPanel2.add(panelPodsumowanie, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCenaProcent;
    private javax.swing.JButton btnRabat;
    private javax.swing.JTextField cenaCzesc;
    private javax.swing.JTextField czesciKoszt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelDoZaplaty;
    private javax.swing.JTextField marzaCzesc;
    private javax.swing.JTextField materialyKoszt;
    private javax.swing.JTextField naprawaKoszt;
    private javax.swing.JPanel panelNaprawa;
    private javax.swing.JPanel panelPodsumowanie;
    private javax.swing.JTextField poRabacieRazem;
    private javax.swing.JTextField podsumowanieKoszt;
    private javax.swing.JTextField rabat;
    private javax.swing.JTable tableCzesci;
    private javax.swing.JTable tableMaterialy;
    private javax.swing.JTable tableNaprawa;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getBtnGroupCenaProcent() {
        return btnGroupCenaProcent;
    }

    public void setBtnGroupCenaProcent(ButtonGroup btnGroupCenaProcent) {
        this.btnGroupCenaProcent = btnGroupCenaProcent;
    }

    public JButton getBtnRabat() {
        return btnRabat;
    }

    public void setBtnRabat(JButton btnRabat) {
        this.btnRabat = btnRabat;
    }

    public JTextField getRabat() {
        return rabat;
    }

    public void setRabat(JTextField rabat) {
        this.rabat = rabat;
    }

    public JTextField getCzesciKoszt() {
        return czesciKoszt;
    }

    public JTextField getCenaCzesc() {
        return cenaCzesc;
    }

    public void setCenaCzesc(JTextField cenaCzesc) {
        this.cenaCzesc = cenaCzesc;
    }

    public JTextField getMarzaCzesc() {
        return marzaCzesc;
    }

    public void setMarzaCzesc(JTextField marzaCzesc) {
        this.marzaCzesc = marzaCzesc;
    }

    public void setCzesciKoszt(JTextField czesciKoszt) {
        this.czesciKoszt = czesciKoszt;
    }

    public JLabel getLabelDoZaplaty() {
        return labelDoZaplaty;
    }

    public void setLabelDoZaplaty(JLabel labelDoZaplaty) {
        this.labelDoZaplaty = labelDoZaplaty;
    }

    public JTextField getMaterialyKoszt() {
        return materialyKoszt;
    }

    public void setMaterialyKoszt(JTextField materialyKoszt) {
        this.materialyKoszt = materialyKoszt;
    }

    public JTextField getNaprawaKoszt() {
        return naprawaKoszt;
    }

    public void setNaprawaKoszt(JTextField naprawaKoszt) {
        this.naprawaKoszt = naprawaKoszt;
    }

    public JPanel getPanelNaprawa() {
        return panelNaprawa;
    }

    public void setPanelNaprawa(JPanel panelNaprawa) {
        this.panelNaprawa = panelNaprawa;
    }

    public JPanel getPanelPodsumowanie() {
        return panelPodsumowanie;
    }

    public void setPanelPodsumowanie(JPanel panelPodsumowanie) {
        this.panelPodsumowanie = panelPodsumowanie;
    }

    public JTextField getPodsumowanieKoszt() {
        return podsumowanieKoszt;
    }

    public void setPodsumowanieKoszt(JTextField podsumowanieKoszt) {
        this.podsumowanieKoszt = podsumowanieKoszt;
    }

    public JTable getTableCzesci() {
        return tableCzesci;
    }

    public void setTableCzesci(JTable tableCzesci) {
        this.tableCzesci = tableCzesci;
    }

    public JTable getTableMaterialy() {
        return tableMaterialy;
    }

    public void setTableMaterialy(JTable tableMaterialy) {
        this.tableMaterialy = tableMaterialy;
    }

    public JTable getTableNaprawa() {
        return tableNaprawa;
    }

    public void setTableNaprawa(JTable tableNaprawa) {
        this.tableNaprawa = tableNaprawa;
    }

    public JTextField getPoRabacieRazem() {
        return poRabacieRazem;
    }

    public void setPoRabacieRazem(JTextField poRabacieRazem) {
        this.poRabacieRazem = poRabacieRazem;
    }

}
