/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naprawa.praca;

import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author mzuralski
 */
public class PodsumowaniePanel extends javax.swing.JPanel {

    /**
     * Creates new form GeografiaStrukturaPanel
     */
    public PodsumowaniePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupCenaProcent = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCzesci = new javax.swing.JTable();
        panelNaprawa = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableNaprawa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMaterialy = new javax.swing.JTable();
        panelPodsumowanie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        podsumowanieKoszt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        naprawaKoszt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        materialyKoszt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        czesciKoszt = new javax.swing.JTextField();
        labelDoZaplaty = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(98, 600));
        setPreferredSize(new java.awt.Dimension(240, 600));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Części"));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(100, 100));

        tableCzesci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane3.setViewportView(tableCzesci);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jScrollPane3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(jPanel4, gridBagConstraints);

        panelNaprawa.setBorder(javax.swing.BorderFactory.createTitledBorder("Naprawa"));
        panelNaprawa.setLayout(new java.awt.GridBagLayout());

        jScrollPane5.setPreferredSize(new java.awt.Dimension(100, 100));

        tableNaprawa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tableNaprawa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelNaprawa.add(jScrollPane5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(panelNaprawa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Materiały"));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jScrollPane4.setPreferredSize(new java.awt.Dimension(100, 100));

        tableMaterialy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(tableMaterialy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(jScrollPane4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(jPanel5, gridBagConstraints);

        panelPodsumowanie.setBorder(javax.swing.BorderFactory.createTitledBorder("Podsumowanie"));
        panelPodsumowanie.setMinimumSize(new java.awt.Dimension(23, 23));
        panelPodsumowanie.setPreferredSize(new java.awt.Dimension(100, 100));
        panelPodsumowanie.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Części");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel1, gridBagConstraints);

        podsumowanieKoszt.setBackground(new java.awt.Color(204, 255, 255));
        podsumowanieKoszt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        podsumowanieKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(podsumowanieKoszt, gridBagConstraints);

        jLabel2.setText("Materiały");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel2, gridBagConstraints);

        naprawaKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(naprawaKoszt, gridBagConstraints);

        jLabel3.setText("Naprawa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel3, gridBagConstraints);

        materialyKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(materialyKoszt, gridBagConstraints);

        jLabel4.setText("PODSUMOWANIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(jLabel4, gridBagConstraints);

        czesciKoszt.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPodsumowanie.add(czesciKoszt, gridBagConstraints);

        labelDoZaplaty.setBackground(new java.awt.Color(255, 204, 204));
        labelDoZaplaty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDoZaplaty.setText("Do zapłaty:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(34, 0, 9, 0);
        panelPodsumowanie.add(labelDoZaplaty, gridBagConstraints);

        jLabel6.setText("zł");
        panelPodsumowanie.add(jLabel6, new java.awt.GridBagConstraints());

        jLabel7.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        panelPodsumowanie.add(jLabel7, gridBagConstraints);

        jLabel8.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelPodsumowanie.add(jLabel8, gridBagConstraints);

        jLabel9.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        panelPodsumowanie.add(jLabel9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.53;
        jPanel2.add(panelPodsumowanie, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupCenaProcent;
    private javax.swing.JTextField czesciKoszt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelDoZaplaty;
    private javax.swing.JTextField materialyKoszt;
    private javax.swing.JTextField naprawaKoszt;
    private javax.swing.JPanel panelNaprawa;
    private javax.swing.JPanel panelPodsumowanie;
    private javax.swing.JTextField podsumowanieKoszt;
    private javax.swing.JTable tableCzesci;
    private javax.swing.JTable tableMaterialy;
    private javax.swing.JTable tableNaprawa;
    // End of variables declaration//GEN-END:variables

    public ButtonGroup getBtnGroupCenaProcent() {
        return btnGroupCenaProcent;
    }

    public void setBtnGroupCenaProcent(ButtonGroup btnGroupCenaProcent) {
        this.btnGroupCenaProcent = btnGroupCenaProcent;
    }

    public JTextField getCzesciKoszt() {
        return czesciKoszt;
    }

    public void setCzesciKoszt(JTextField czesciKoszt) {
        this.czesciKoszt = czesciKoszt;
    }

    public JLabel getLabelDoZaplaty() {
        return labelDoZaplaty;
    }

    public void setLabelDoZaplaty(JLabel labelDoZaplaty) {
        this.labelDoZaplaty = labelDoZaplaty;
    }

    public JTextField getMaterialyKoszt() {
        return materialyKoszt;
    }

    public void setMaterialyKoszt(JTextField materialyKoszt) {
        this.materialyKoszt = materialyKoszt;
    }

    public JTextField getNaprawaKoszt() {
        return naprawaKoszt;
    }

    public void setNaprawaKoszt(JTextField naprawaKoszt) {
        this.naprawaKoszt = naprawaKoszt;
    }

    public JPanel getPanelNaprawa() {
        return panelNaprawa;
    }

    public void setPanelNaprawa(JPanel panelNaprawa) {
        this.panelNaprawa = panelNaprawa;
    }

    public JPanel getPanelPodsumowanie() {
        return panelPodsumowanie;
    }

    public void setPanelPodsumowanie(JPanel panelPodsumowanie) {
        this.panelPodsumowanie = panelPodsumowanie;
    }

    public JTextField getPodsumowanieKoszt() {
        return podsumowanieKoszt;
    }

    public void setPodsumowanieKoszt(JTextField podsumowanieKoszt) {
        this.podsumowanieKoszt = podsumowanieKoszt;
    }

    public JTable getTableCzesci() {
        return tableCzesci;
    }

    public void setTableCzesci(JTable tableCzesci) {
        this.tableCzesci = tableCzesci;
    }

    public JTable getTableMaterialy() {
        return tableMaterialy;
    }

    public void setTableMaterialy(JTable tableMaterialy) {
        this.tableMaterialy = tableMaterialy;
    }

    public JTable getTableNaprawa() {
        return tableNaprawa;
    }

    public void setTableNaprawa(JTable tableNaprawa) {
        this.tableNaprawa = tableNaprawa;
    }

}
