/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naprawa.praca;

import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import swing.UITogglePanel;

/**
 *
 * @author jmaj
 */
public class PracaPanel extends javax.swing.JPanel {

    private final PodsumowaniePanel podsumowaniePanel = new PodsumowaniePanel();
    private final PracaZaplataPanel czesciPanel = new PracaZaplataPanel();
    private final PracaZaplataPanel materialyPanel = new PracaZaplataPanel();
    private final PracaZaplataPanel naprawaPanel = new PracaZaplataPanel();
    private final PracaInfoPanel infoPanel = new PracaInfoPanel();

    /**
     * Creates new form PracaPanel
     */
    public PracaPanel() {
        initComponents();
        tglInfoNaprawa.initInternalPanel(infoPanel);
        tglCzesci.initInternalPanel(czesciPanel);
        tglKosztNaprawy.initInternalPanel(naprawaPanel);
        tglPodsumowanie.initInternalPanel(podsumowaniePanel);
        tglMaterialy.initInternalPanel(materialyPanel);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        tglInfoNaprawa = new swing.UITogglePanel();
        tglCzesci = new swing.UITogglePanel();
        tglKosztNaprawy = new swing.UITogglePanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        tglPodsumowanie = new swing.UITogglePanel();
        tglMaterialy = new swing.UITogglePanel();
        panelPrzyciski = new javax.swing.JPanel();
        btnRezygnuj = new javax.swing.JButton();
        btnZakonczPrace = new javax.swing.JButton();
        btnDrukuj = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(447, 63));
        setPreferredSize(new java.awt.Dimension(1002, 153));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        tglInfoNaprawa.setBackground(new java.awt.Color(132, 191, 180));
        tglInfoNaprawa.setTitleFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tglInfoNaprawa.setTytul("INFORMACJE O NAPRAWIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tglInfoNaprawa, gridBagConstraints);

        tglCzesci.setBackground(new java.awt.Color(12, 126, 189));
        tglCzesci.setTitleFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tglCzesci.setTytul("CZĘŚCI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tglCzesci, gridBagConstraints);

        tglKosztNaprawy.setBackground(new java.awt.Color(12, 126, 189));
        tglKosztNaprawy.setTitleFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tglKosztNaprawy.setTytul("KOSZT NAPRAWY\n");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tglKosztNaprawy, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(filler2, gridBagConstraints);

        tglPodsumowanie.setBackground(new java.awt.Color(132, 191, 180));
        tglPodsumowanie.setTitleFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tglPodsumowanie.setTytul("PODSUMOWANIE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tglPodsumowanie, gridBagConstraints);

        tglMaterialy.setBackground(new java.awt.Color(132, 191, 180));
        tglMaterialy.setTitleFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tglMaterialy.setTytul("MATERIAŁY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(tglMaterialy, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        panelPrzyciski.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPrzyciski.setMaximumSize(new java.awt.Dimension(32767, 40));
        panelPrzyciski.setMinimumSize(new java.awt.Dimension(447, 40));
        panelPrzyciski.setPreferredSize(new java.awt.Dimension(447, 40));
        panelPrzyciski.setRequestFocusEnabled(false);
        panelPrzyciski.setLayout(new java.awt.GridBagLayout());

        btnRezygnuj.setText("Rezygnuj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPrzyciski.add(btnRezygnuj, gridBagConstraints);

        btnZakonczPrace.setText("Zakończ prace");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPrzyciski.add(btnZakonczPrace, gridBagConstraints);

        btnDrukuj.setText("Drukuj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelPrzyciski.add(btnDrukuj, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        add(panelPrzyciski, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrukuj;
    private javax.swing.JButton btnRezygnuj;
    private javax.swing.JButton btnZakonczPrace;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrzyciski;
    private swing.UITogglePanel tglCzesci;
    private swing.UITogglePanel tglInfoNaprawa;
    private swing.UITogglePanel tglKosztNaprawy;
    private swing.UITogglePanel tglMaterialy;
    private swing.UITogglePanel tglPodsumowanie;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnDrukuj() {
        return btnDrukuj;
    }

    public void setBtnDrukuj(JButton btnDrukuj) {
        this.btnDrukuj = btnDrukuj;
    }

    public JButton getBtnRezygnuj() {
        return btnRezygnuj;
    }

    public void setBtnRezygnuj(JButton btnRezygnuj) {
        this.btnRezygnuj = btnRezygnuj;
    }

    public JButton getBtnZakonczPrace() {
        return btnZakonczPrace;
    }

    public void setBtnZakonczPrace(JButton btnZakonczPrace) {
        this.btnZakonczPrace = btnZakonczPrace;
    }

    public Box.Filler getFiller2() {
        return filler2;
    }

    public void setFiller2(Box.Filler filler2) {
        this.filler2 = filler2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPanelPrzyciski() {
        return panelPrzyciski;
    }

    public void setPanelPrzyciski(JPanel panelPrzyciski) {
        this.panelPrzyciski = panelPrzyciski;
    }

    public UITogglePanel getTglCzesci() {
        return tglCzesci;
    }

    public void setTglCzesci(UITogglePanel tglCzesci) {
        this.tglCzesci = tglCzesci;
    }

    public UITogglePanel getTglInfoNaprawa() {
        return tglInfoNaprawa;
    }

    public void setTglInfoNaprawa(UITogglePanel tglInfoNaprawa) {
        this.tglInfoNaprawa = tglInfoNaprawa;
    }

    public UITogglePanel getTglKosztNaprawy() {
        return tglKosztNaprawy;
    }

    public void setTglKosztNaprawy(UITogglePanel tglKosztNaprawy) {
        this.tglKosztNaprawy = tglKosztNaprawy;
    }

    public UITogglePanel getTglMaterialy() {
        return tglMaterialy;
    }

    public void setTglMaterialy(UITogglePanel tglMaterialy) {
        this.tglMaterialy = tglMaterialy;
    }

    public UITogglePanel getTglPodsumowanie() {
        return tglPodsumowanie;
    }

    public void setTglPodsumowanie(UITogglePanel tglPodsumowanie) {
        this.tglPodsumowanie = tglPodsumowanie;
    }

    public List<UITogglePanel> getListaTglPanel() {
        List<UITogglePanel> lista = new ArrayList<>();
        lista.add(tglCzesci);
        lista.add(tglPodsumowanie);
        return lista;
    }

}
