/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naprawa.praca;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author mzuralski
 */
public class PracaZaplataPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeografiaStrukturaPanel
     */
    public PracaZaplataPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupCenaProcent = new javax.swing.ButtonGroup();
        panelWybor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opis = new javax.swing.JTextField();
        labelCenaKoszt = new javax.swing.JLabel();
        kosztCenaPodst = new javax.swing.JTextField();
        btnProcent = new javax.swing.JRadioButton();
        btnKwota = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        dodajDoCeny = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        labelProcentZl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        suma = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radioBrak = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnDodaj = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(356, 300));
        setPreferredSize(new java.awt.Dimension(919, 300));
        setLayout(new java.awt.GridBagLayout());

        panelWybor.setBorder(javax.swing.BorderFactory.createTitledBorder("Koszty naprawy"));
        panelWybor.setMinimumSize(new java.awt.Dimension(100, 100));
        panelWybor.setPreferredSize(new java.awt.Dimension(100, 100));
        panelWybor.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Opis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(jLabel1, gridBagConstraints);

        opis.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(opis, gridBagConstraints);

        labelCenaKoszt.setText("Koszt/Cena");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(labelCenaKoszt, gridBagConstraints);

        kosztCenaPodst.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(kosztCenaPodst, gridBagConstraints);

        btnGroupCenaProcent.add(btnProcent);
        btnProcent.setText("Procent");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(btnProcent, gridBagConstraints);

        btnGroupCenaProcent.add(btnKwota);
        btnKwota.setText("Kwota");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(btnKwota, gridBagConstraints);

        jLabel3.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(dodajDoCeny, gridBagConstraints);

        jLabel4.setText("+");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(jLabel4, gridBagConstraints);

        labelProcentZl.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(labelProcentZl, gridBagConstraints);

        jLabel6.setText("=");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(suma, gridBagConstraints);

        jLabel7.setText("zł");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(jLabel7, gridBagConstraints);

        btnGroupCenaProcent.add(radioBrak);
        radioBrak.setSelected(true);
        radioBrak.setText("Brak");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        panelWybor.add(radioBrak, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnDodaj.setText(">");
        btnDodaj.setPreferredSize(new java.awt.Dimension(60, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanel3.add(btnDodaj, gridBagConstraints);

        btnUsun.setText("<");
        btnUsun.setPreferredSize(new java.awt.Dimension(60, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 3, 5);
        jPanel3.add(btnUsun, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        panelWybor.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(panelWybor, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Opis", "Koszt"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDodaj() {
        return btnDodaj;
    }

    public void setBtnDodaj(JButton btnDodaj) {
        this.btnDodaj = btnDodaj;
    }

    public ButtonGroup getBtnGroupCenaProcent() {
        return btnGroupCenaProcent;
    }

    public void setBtnGroupCenaProcent(ButtonGroup btnGroupCenaProcent) {
        this.btnGroupCenaProcent = btnGroupCenaProcent;
    }

    public JRadioButton getBtnKwota() {
        return btnKwota;
    }

    public void setBtnKwota(JRadioButton btnKwota) {
        this.btnKwota = btnKwota;
    }

    public JRadioButton getBtnProcent() {
        return btnProcent;
    }

    public void setBtnProcent(JRadioButton btnProcent) {
        this.btnProcent = btnProcent;
    }

    public JButton getBtnUsun() {
        return btnUsun;
    }

    public void setBtnUsun(JButton btnUsun) {
        this.btnUsun = btnUsun;
    }

    public JTextField getDodajDoCeny() {
        return dodajDoCeny;
    }

    public void setDodajDoCeny(JTextField dodajDoCeny) {
        this.dodajDoCeny = dodajDoCeny;
    }

    public JTextField getKosztCenaPodst() {
        return kosztCenaPodst;
    }

    public void setKosztCenaPodst(JTextField kosztCenaPodst) {
        this.kosztCenaPodst = kosztCenaPodst;
    }

    public JLabel getLabelCenaKoszt() {
        return labelCenaKoszt;
    }

    public void setLabelCenaKoszt(JLabel labelCenaKoszt) {
        this.labelCenaKoszt = labelCenaKoszt;
    }

    public JLabel getLabelProcentZl() {
        return labelProcentZl;
    }

    public void setLabelProcentZl(JLabel labelProcentZl) {
        this.labelProcentZl = labelProcentZl;
    }

    public JTextField getOpis() {
        return opis;
    }

    public void setOpis(JTextField opis) {
        this.opis = opis;
    }

    public JPanel getPanelWybor() {
        return panelWybor;
    }

    public void setPanelWybor(JPanel panelWybor) {
        this.panelWybor = panelWybor;
    }

    public JRadioButton getRadioBrak() {
        return radioBrak;
    }

    public void setRadioBrak(JRadioButton radioBrak) {
        this.radioBrak = radioBrak;
    }

    public JTextField getSuma() {
        return suma;
    }

    public void setSuma(JTextField suma) {
        this.suma = suma;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.ButtonGroup btnGroupCenaProcent;
    private javax.swing.JRadioButton btnKwota;
    private javax.swing.JRadioButton btnProcent;
    private javax.swing.JButton btnUsun;
    private javax.swing.JTextField dodajDoCeny;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kosztCenaPodst;
    private javax.swing.JLabel labelCenaKoszt;
    private javax.swing.JLabel labelProcentZl;
    private javax.swing.JTextField opis;
    private javax.swing.JPanel panelWybor;
    private javax.swing.JRadioButton radioBrak;
    private javax.swing.JTextField suma;
    // End of variables declaration//GEN-END:variables
}
