/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platnosci;

import Model.TO_PaymentCompany;
import adm.Baks.BaksSessionBean;
import dao.DaoFactory;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author RobertM
 */
public class DodanieFirmyDialog extends javax.swing.JDialog {

    private TO_PaymentCompany company;
    private Connection connection;
    private DaoFactory daoFactory;

    /**
     * Creates new form DodanieFirmyDialog
     */
    public DodanieFirmyDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void initConnection(Connection conn, DaoFactory factory) {
        this.connection = conn;
        this.daoFactory = factory;
        init();
    }

    private void init() {
        btnZapiszFirme.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                akcjaDodajFirme();
            }
        });

        btnWyjdzFirma.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                akcjaWyjdz();
            }
        });
    }

    public void akcjaDodajFirme() {
        czytajFormatke();
        if (company.getName() == null || company.getName().isEmpty()) {
            BaksSessionBean.getInstance().fireMessage(this, "Dodanie nowej firmy", "Wpisz nazwe firmy!");
            return;
        }
        try {
            daoFactory.getDaoInvoice().dodajFirme(connection, company);
            BaksSessionBean.getInstance().fireMessage(this, "Zapis", "Poprawnie zapisano nową firme.");
            this.dispose();
        } catch (Exception ex) {

        }
    }

    public void czytajFormatke() {
        company = new TO_PaymentCompany();
        company.setName(textNazwaFirmy.getText());
        company.setAdress(textAdresFirmy.getText());
        company.setPhone(textTelefon.getText());
        company.setNip(textNip.getText());
    }

    public void akcjaWyjdz() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textNazwaFirmy = new javax.swing.JTextField();
        textAdresFirmy = new javax.swing.JTextField();
        textTelefon = new javax.swing.JTextField();
        textNip = new javax.swing.JTextField();
        btnZapiszFirme = new javax.swing.JButton();
        btnWyjdzFirma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nowa firma");

        jLabel1.setText("Nazwa");

        jLabel2.setText("Adres");

        jLabel3.setText("Telefon");

        jLabel4.setText("Nip");

        btnZapiszFirme.setText("Zapisz");

        btnWyjdzFirma.setText("Wyjdz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNazwaFirmy)
                    .addComponent(textAdresFirmy, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnZapiszFirme)
                            .addGap(18, 18, 18)
                            .addComponent(btnWyjdzFirma))
                        .addComponent(textNip, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNazwaFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textAdresFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZapiszFirme)
                    .addComponent(btnWyjdzFirma))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public JButton getBtnWyjdzFirma() {
        return btnWyjdzFirma;
    }

    public void setBtnWyjdzFirma(JButton btnWyjdzFirma) {
        this.btnWyjdzFirma = btnWyjdzFirma;
    }

    public JButton getBtnZapiszFirme() {
        return btnZapiszFirme;
    }

    public void setBtnZapiszFirme(JButton btnZapiszFirme) {
        this.btnZapiszFirme = btnZapiszFirme;
    }

    public JTextField getTextAdresFirmy() {
        return textAdresFirmy;
    }

    public void setTextAdresFirmy(JTextField textAdresFirmy) {
        this.textAdresFirmy = textAdresFirmy;
    }

    public JTextField getTextNazwaFirmy() {
        return textNazwaFirmy;
    }

    public void setTextNazwaFirmy(JTextField textNazwaFirmy) {
        this.textNazwaFirmy = textNazwaFirmy;
    }

    public JTextField getTextNip() {
        return textNip;
    }

    public void setTextNip(JTextField textNip) {
        this.textNip = textNip;
    }

    public JTextField getTextTelefon() {
        return textTelefon;
    }

    public void setTextTelefon(JTextField textTelefon) {
        this.textTelefon = textTelefon;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWyjdzFirma;
    private javax.swing.JButton btnZapiszFirme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textAdresFirmy;
    private javax.swing.JTextField textNazwaFirmy;
    private javax.swing.JTextField textNip;
    private javax.swing.JTextField textTelefon;
    // End of variables declaration//GEN-END:variables
}
