/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package platnosci;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Robert M
 */
public class PrzegladaniePlatnosciPanel extends javax.swing.JPanel {

    /**
     * Creates new form NaprawaZapisPanel
     */
    public PrzegladaniePlatnosciPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sortowanie = new javax.swing.ButtonGroup();
        terminSortowanie = new javax.swing.ButtonGroup();
        kwotaSortowanie = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnRezygnuj = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnWybierz = new javax.swing.JButton();
        btnUsun = new javax.swing.JButton();
        btnDrukuj = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        radioZaplacone = new javax.swing.JRadioButton();
        radioNieZaplacone = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        radioAnulowane = new javax.swing.JRadioButton();
        btnSzukaj = new javax.swing.JButton();
        btnWyczysc = new javax.swing.JButton();
        doZaplatyText = new javax.swing.JTextField();
        labelDoZaplaty = new javax.swing.JLabel();
        zlLabel = new javax.swing.JLabel();
        radioMalejacoTermin = new javax.swing.JRadioButton();
        radioRosnacoTermin = new javax.swing.JRadioButton();
        radioKwotaMalejaco = new javax.swing.JRadioButton();
        radioKwotaRosnaco = new javax.swing.JRadioButton();
        radioTerminSortowanie = new javax.swing.JRadioButton();
        radioKwotaSortowanie = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Płatności"));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        panelBtn.setBackground(new java.awt.Color(102, 102, 102));

        btnRezygnuj.setText("Rezygnuj");

        btnDodaj.setText("Dodaj");

        btnWybierz.setText("Wybierz");

        btnUsun.setText("Usuń");

        btnDrukuj.setText("Drukuj");

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnDrukuj)
                .addGap(230, 230, 230)
                .addComponent(btnWybierz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRezygnuj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRezygnuj)
                    .addComponent(btnDodaj)
                    .addComponent(btnWybierz)
                    .addComponent(btnUsun)
                    .addComponent(btnDrukuj))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        buttonGroup1.add(radioZaplacone);
        radioZaplacone.setText("Zapłacone");

        buttonGroup1.add(radioNieZaplacone);
        radioNieZaplacone.setText("Nie zapłacone");

        jLabel3.setText("Status");

        jLabel4.setText("Wyszukiwanie");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marka", "Model", "Termin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
        }

        buttonGroup1.add(radioAnulowane);
        radioAnulowane.setText("Anulowane");

        btnSzukaj.setText("Szukaj");

        btnWyczysc.setText("Wyczyść");

        labelDoZaplaty.setText("Suma do zapłaty");

        zlLabel.setText("zł");

        terminSortowanie.add(radioMalejacoTermin);
        radioMalejacoTermin.setText("malejąco");

        terminSortowanie.add(radioRosnacoTermin);
        radioRosnacoTermin.setText("rosnąco");

        kwotaSortowanie.add(radioKwotaMalejaco);
        radioKwotaMalejaco.setText("malejąco");

        kwotaSortowanie.add(radioKwotaRosnaco);
        radioKwotaRosnaco.setText("rosnąco");

        sortowanie.add(radioTerminSortowanie);
        radioTerminSortowanie.setText("Termin płatności");

        sortowanie.add(radioKwotaSortowanie);
        radioKwotaSortowanie.setText("Kwota");

        jLabel2.setText("SORTOWANIE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(radioZaplacone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioNieZaplacone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioAnulowane))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4)
                                .addGap(506, 506, 506)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioRosnacoTermin)
                            .addComponent(radioMalejacoTermin)
                            .addComponent(radioTerminSortowanie))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioKwotaSortowanie)
                            .addComponent(radioKwotaMalejaco)
                            .addComponent(radioKwotaRosnaco))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnSzukaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnWyczysc)
                .addGap(288, 288, 288)
                .addComponent(labelDoZaplaty, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doZaplatyText, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zlLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radioTerminSortowanie)
                    .addComponent(radioKwotaSortowanie)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioMalejacoTermin)
                            .addComponent(radioKwotaMalejaco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioRosnacoTermin)
                            .addComponent(radioKwotaRosnaco)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(radioZaplacone)
                        .addComponent(radioNieZaplacone)
                        .addComponent(radioAnulowane)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSzukaj)
                    .addComponent(btnWyczysc)
                    .addComponent(doZaplatyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDoZaplaty)
                    .addComponent(zlLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDodaj() {
        return btnDodaj;
    }

    public void setBtnDodaj(JButton btnDodaj) {
        this.btnDodaj = btnDodaj;
    }

    public JButton getBtnRezygnuj() {
        return btnRezygnuj;
    }

    public void setBtnRezygnuj(JButton btnRezygnuj) {
        this.btnRezygnuj = btnRezygnuj;
    }

    public JButton getBtnSzukaj() {
        return btnSzukaj;
    }

    public void setBtnSzukaj(JButton btnSzukaj) {
        this.btnSzukaj = btnSzukaj;
    }

    public JButton getBtnUsun() {
        return btnUsun;
    }

    public void setBtnUsun(JButton btnUsun) {
        this.btnUsun = btnUsun;
    }

    public JButton getBtnDrukuj() {
        return btnDrukuj;
    }

    public void setBtnDrukuj(JButton btnDrukuj) {
        this.btnDrukuj = btnDrukuj;
    }

    public JButton getBtnWybierz() {
        return btnWybierz;
    }

    public void setBtnWybierz(JButton btnWybierz) {
        this.btnWybierz = btnWybierz;
    }

    public JButton getBtnWyczysc() {
        return btnWyczysc;
    }

    public void setBtnWyczysc(JButton btnWyczysc) {
        this.btnWyczysc = btnWyczysc;
    }

    public JRadioButton getRadioAnulowane() {
        return radioAnulowane;
    }

    public void setRadioAnulowane(JRadioButton radioAnulowane) {
        this.radioAnulowane = radioAnulowane;
    }

    public JRadioButton getRadioNieZaplacone() {
        return radioNieZaplacone;
    }

    public void setRadioNieZaplacone(JRadioButton radioNieZaplacone) {
        this.radioNieZaplacone = radioNieZaplacone;
    }

    public JRadioButton getRadioZaplacone() {
        return radioZaplacone;
    }

    public void setRadioZaplacone(JRadioButton radioZaplacone) {
        this.radioZaplacone = radioZaplacone;
    }

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }

    public JTextField getDoZaplatyText() {
        return doZaplatyText;
    }

    public void setDoZaplatyText(JTextField doZaplatyText) {
        this.doZaplatyText = doZaplatyText;
    }

    public JLabel getLabelDoZaplaty() {
        return labelDoZaplaty;
    }

    public void setLabelDoZaplaty(JLabel labelDoZaplaty) {
        this.labelDoZaplaty = labelDoZaplaty;
    }

    public JLabel getZlLabel() {
        return zlLabel;
    }

    public void setZlLabel(JLabel zlLabel) {
        this.zlLabel = zlLabel;
    }

    public JRadioButton getRadioKwotaMalejaco() {
        return radioKwotaMalejaco;
    }

    public void setRadioKwotaMalejaco(JRadioButton radioKwotaMalejaco) {
        this.radioKwotaMalejaco = radioKwotaMalejaco;
    }

    public JRadioButton getRadioKwotaRosnaco() {
        return radioKwotaRosnaco;
    }

    public void setRadioKwotaRosnaco(JRadioButton radioKwotaRosnaco) {
        this.radioKwotaRosnaco = radioKwotaRosnaco;
    }

    public JRadioButton getRadioKwotaSortowanie() {
        return radioKwotaSortowanie;
    }

    public void setRadioKwotaSortowanie(JRadioButton radioKwotaSortowanie) {
        this.radioKwotaSortowanie = radioKwotaSortowanie;
    }

    public JRadioButton getRadioMalejacoTermin() {
        return radioMalejacoTermin;
    }

    public void setRadioMalejacoTermin(JRadioButton radioMalejacoTermin) {
        this.radioMalejacoTermin = radioMalejacoTermin;
    }

    public JRadioButton getRadioRosnacoTermin() {
        return radioRosnacoTermin;
    }

    public void setRadioRosnacoTermin(JRadioButton radioRosnacoTermin) {
        this.radioRosnacoTermin = radioRosnacoTermin;
    }

    public JRadioButton getRadioTerminSortowanie() {
        return radioTerminSortowanie;
    }

    public void setRadioTerminSortowanie(JRadioButton radioTerminSortowanie) {
        this.radioTerminSortowanie = radioTerminSortowanie;
    }

    public ButtonGroup getSortowanie() {
        return sortowanie;
    }

    public void setSortowanie(ButtonGroup sortowanie) {
        this.sortowanie = sortowanie;
    }

    public ButtonGroup getTerminSortowanie() {
        return terminSortowanie;
    }

    public void setTerminSortowanie(ButtonGroup terminSortowanie) {
        this.terminSortowanie = terminSortowanie;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDrukuj;
    private javax.swing.JButton btnRezygnuj;
    private javax.swing.JButton btnSzukaj;
    private javax.swing.JButton btnUsun;
    private javax.swing.JButton btnWybierz;
    private javax.swing.JButton btnWyczysc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField doZaplatyText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup kwotaSortowanie;
    private javax.swing.JLabel labelDoZaplaty;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JRadioButton radioAnulowane;
    private javax.swing.JRadioButton radioKwotaMalejaco;
    private javax.swing.JRadioButton radioKwotaRosnaco;
    private javax.swing.JRadioButton radioKwotaSortowanie;
    private javax.swing.JRadioButton radioMalejacoTermin;
    private javax.swing.JRadioButton radioNieZaplacone;
    private javax.swing.JRadioButton radioRosnacoTermin;
    private javax.swing.JRadioButton radioTerminSortowanie;
    private javax.swing.JRadioButton radioZaplacone;
    private javax.swing.ButtonGroup sortowanie;
    private javax.swing.JTable table;
    private javax.swing.ButtonGroup terminSortowanie;
    private javax.swing.JLabel zlLabel;
    // End of variables declaration//GEN-END:variables
}
